package com.boss.xtrain.permission.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;
import lombok.Data;

import javax.persistence.Table;
import java.util.Date;

/**
 * @author 53534秦昀清
 * @date 2020.07.06
 */
@Data
@Table(name = "t_dictionary")
public class Dictionary extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.name
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.category
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.value
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.remark
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String remark;

}