package com.boss.xtrain.permission.pojo.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.Column;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * @author 53534秦昀清
 * @date 2020.07.06
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Table(name = "t_system_param")
public class SystemParam extends BaseSystemEntity {

    @Column(name = "t_o_id")
    private Long organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.param_type
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "param_type")
    private String paramType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.param
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "param")
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.value
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "value")
    private String value;

    /**
     *  当前行的版初始为0 每次数据变动则加1
     */
    @Column(name = "version")
    private Long version;
}