package com.boss.xtrain.permission.pojo.entity;

import lombok.Data;

import javax.persistence.Table;

/**
 * @author 53534秦昀清
 * @date 2020.07.06
 */
@Data
@Table(name = "t_system_param")
public class SystemParam {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.param_type
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String paramType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.param
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.value
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String value;

}