package com.boss.xtrain.permission.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * @author 53534秦昀清
 * @date 2020.07.06
 */
@Data
@Table(name = "t_user_online_info")
public class UserOnlineInfo{

    /**
     * 主键id
     */
    @Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.t_u_id
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "t_u_id")
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.code
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "code")
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.name
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "name")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.ip
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "ip")
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.online_time
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "online_time")
    private Date onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.offline_time
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "offline_time")
    private Date offlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.stop_time
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    @Column(name = "stop_time")
    private Integer stopTime;

    /**
     * 状态
     */
    @Column(name = "status")
    private Integer status;
}