package com.boss.xtrain.permission.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;
import lombok.Data;

import javax.persistence.Table;
import java.util.Date;

/**
 * @author 53534秦昀清
 * @date 2020.07.06
 */
@Data
@Table(name = "t_user_online_info")
public class UserOnlineInfo extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.t_u_id
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.code
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.name
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.ip
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.online_time
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private Date onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.offline_time
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private Date offlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_online_info.stop_time
     *
     * @mbg.generated Mon Jul 06 12:22:48 CST 2020
     */
    private Integer stopTime;

}