package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;

import javax.persistence.Table;
import java.util.Date;

@Table(name = "t_exam_publish_record_user")
public class ExamPublishToUser extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.t_p_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.t_u_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long tUId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.status
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.company_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.org_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.created_by
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.created_time
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.updated_by
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.updated_time
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.version
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.id
     *
     * @return the value of t_exam_publish_record_user.id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.id
     *
     * @param id the value for t_exam_publish_record_user.id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.t_p_id
     *
     * @return the value of t_exam_publish_record_user.t_p_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.t_p_id
     *
     * @param paperId the value for t_exam_publish_record_user.t_p_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.t_u_id
     *
     * @return the value of t_exam_publish_record_user.t_u_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public Long gettUId() {
        return tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.t_u_id
     *
     * @param tUId the value for t_exam_publish_record_user.t_u_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public void settUId(Long tUId) {
        this.tUId = tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.status
     *
     * @return the value of t_exam_publish_record_user.status
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.status
     *
     * @param status the value for t_exam_publish_record_user.status
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.company_id
     *
     * @return the value of t_exam_publish_record_user.company_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.company_id
     *
     * @param companyId the value for t_exam_publish_record_user.company_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.org_id
     *
     * @return the value of t_exam_publish_record_user.org_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.org_id
     *
     * @param orgId the value for t_exam_publish_record_user.org_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.created_by
     *
     * @return the value of t_exam_publish_record_user.created_by
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.created_by
     *
     * @param createdBy the value for t_exam_publish_record_user.created_by
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.created_time
     *
     * @return the value of t_exam_publish_record_user.created_time
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.created_time
     *
     * @param createdTime the value for t_exam_publish_record_user.created_time
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.updated_by
     *
     * @return the value of t_exam_publish_record_user.updated_by
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.updated_by
     *
     * @param updatedBy the value for t_exam_publish_record_user.updated_by
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.updated_time
     *
     * @return the value of t_exam_publish_record_user.updated_time
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.updated_time
     *
     * @param updatedTime the value for t_exam_publish_record_user.updated_time
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.version
     *
     * @return the value of t_exam_publish_record_user.version
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.version
     *
     * @param version the value for t_exam_publish_record_user.version
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Override
    public void setVersion(Long version) {
        this.version = version;
    }
}