package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

@Table(name = "t_exam_record")
public class ExamRecord extends BaseEntity {
    /**
     * 考试发布记录id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.t_pr_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "t_pr_id")
    private Long publishId;

    /**
     * 考生id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "t_p_id")
    private Long examPeople;

    /**
     * 计划开始时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.plan_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "plan_start_time")
    private Date planStartTime;

    /**
     * 计划结束时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.plan_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "plan_end_time")
    private Date planEndTime;

    /**
     * 实际开始时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.actual_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "actual_start_time")
    private Date actualStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.actual_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "actual_end_time")
    private Date actualEndTime;

    /**
     * 客观题登封
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.objective_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "objective_subject_score")
    private BigDecimal objectiveSubjectScore;

    /**
     * 阅卷官id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.t_u_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "t_u_id")
    private Long markUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.subjectvie_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "subjective_subject_score")
    private BigDecimal subjectiveSubjectScore;

    /**
     * 阅卷分配时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.marking_assign_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "marking_assign_time")
    private Date markingAssignTime;

    /**
     * 总分
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "score")
    private BigDecimal score;

    /**
     * 能力标签
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.system_evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "system_evaluate")
    private String systemEvaluate;

    public Long getMarkUserId() {
        return markUserId;
    }

    public void setMarkUserId(Long markUserId) {
        this.markUserId = markUserId;
    }

    public BigDecimal getSubjectiveSubjectScore() {
        return subjectiveSubjectScore;
    }

    public void setSubjectiveSubjectScore(BigDecimal subjectiveSubjectScore) {
        this.subjectiveSubjectScore = subjectiveSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.t_pr_id
     *
     * @return the value of t_exam_record.t_pr_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.t_pr_id
     *
     * @param publishId the value for t_exam_record.t_pr_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPublishId(Long publishId) {
        this.publishId = publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.t_p_id
     *
     * @return the value of t_exam_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getExamPeople() {
        return examPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.t_p_id
     *
     * @param examPeople the value for t_exam_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setExamPeople(Long examPeople) {
        this.examPeople = examPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.plan_start_time
     *
     * @return the value of t_exam_record.plan_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getPlanStartTime() {
        return planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.plan_start_time
     *
     * @param planStartTime the value for t_exam_record.plan_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.plan_end_time
     *
     * @return the value of t_exam_record.plan_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.plan_end_time
     *
     * @param planEndTime the value for t_exam_record.plan_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.actual_start_time
     *
     * @return the value of t_exam_record.actual_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getActualStartTime() {
        return actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.actual_start_time
     *
     * @param actualStartTime the value for t_exam_record.actual_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setActualStartTime(Date actualStartTime) {
        this.actualStartTime = actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.actual_end_time
     *
     * @return the value of t_exam_record.actual_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getActualEndTime() {
        return actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.actual_end_time
     *
     * @param actualEndTime the value for t_exam_record.actual_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setActualEndTime(Date actualEndTime) {
        this.actualEndTime = actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.objective_subject_score
     *
     * @return the value of t_exam_record.objective_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public BigDecimal getObjectiveSubjectScore() {
        return objectiveSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.objective_subject_score
     *
     * @param objectiveSubjectScore the value for t_exam_record.objective_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setObjectiveSubjectScore(BigDecimal objectiveSubjectScore) {
        this.objectiveSubjectScore = objectiveSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.marking_assign_time
     *
     * @return the value of t_exam_record.marking_assign_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getMarkingAssignTime() {
        return markingAssignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.marking_assign_time
     *
     * @param markingAssignTime the value for t_exam_record.marking_assign_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMarkingAssignTime(Date markingAssignTime) {
        this.markingAssignTime = markingAssignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.score
     *
     * @return the value of t_exam_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.score
     *
     * @param score the value for t_exam_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.system_evaluate
     *
     * @return the value of t_exam_record.system_evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getSystemEvaluate() {
        return systemEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.system_evaluate
     *
     * @param systemEvaluate the value for t_exam_record.system_evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setSystemEvaluate(String systemEvaluate) {
        this.systemEvaluate = systemEvaluate;
    }

}