package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "t_exam_people")
public class ExamPeople extends BaseEntity {

    /**
     * 手机号
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.mobile
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "mobile")
    private String mobile;

    /**
     * 邮箱
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.email
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "email")
    private String email;

    /**
     * 密码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.password
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "password")
    private String password;

    /**
     * 姓名
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.name
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "name")
    private String name;

    /**
     * 性别
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.sex
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "sex")
    private Boolean sex;

    /**
     * 院校
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.university
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "university")
    private String university;

    /**
     * 专业
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.major
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "major")
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.photo_url
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "photo_url")
    private String photoUrl;

    /**
     * 毕业时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.graduate_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "graduate_time")
    private Date graduateTime;

    /**
     * 获奖情况
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.prizie_info
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "award_info")
    private String awardInfo;

    /**
     * 备注
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_people.remark
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "remark")
    private String remark;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.mobile
     *
     * @return the value of t_exam_people.mobile
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.mobile
     *
     * @param mobile the value for t_exam_people.mobile
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.email
     *
     * @return the value of t_exam_people.email
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.email
     *
     * @param email the value for t_exam_people.email
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.password
     *
     * @return the value of t_exam_people.password
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.password
     *
     * @param password the value for t_exam_people.password
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.name
     *
     * @return the value of t_exam_people.name
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.name
     *
     * @param name the value for t_exam_people.name
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.sex
     *
     * @return the value of t_exam_people.sex
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.sex
     *
     * @param sex the value for t_exam_people.sex
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.university
     *
     * @return the value of t_exam_people.university
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.university
     *
     * @param university the value for t_exam_people.university
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setUniversity(String university) {
        this.university = university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.major
     *
     * @return the value of t_exam_people.major
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.major
     *
     * @param major the value for t_exam_people.major
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.photo_url
     *
     * @return the value of t_exam_people.photo_url
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.photo_url
     *
     * @param photoUrl the value for t_exam_people.photo_url
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.graduate_time
     *
     * @return the value of t_exam_people.graduate_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getGraduateTime() {
        return graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.graduate_time
     *
     * @param graduateTime the value for t_exam_people.graduate_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setGraduateTime(Date graduateTime) {
        this.graduateTime = graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.prizie_info
     *
     * @return the value of t_exam_people.prizie_info
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getAwardInfo() {
        return awardInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.prizie_info
     *
     * @param awardInfo the value for t_exam_people.prizie_info
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setAwardInfo(String awardInfo) {
        this.awardInfo = awardInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_people.remark
     *
     * @return the value of t_exam_people.remark
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_people.remark
     *
     * @param remark the value for t_exam_people.remark
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

}