package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "t_exam_publish_record_user")
public class ExamPublishToUser extends BaseEntity {

    /**
     * 考试发布记录id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.t_p_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Column(name = "t_p_id")
    private Long publishId;

    /**
     * 考试阅卷官id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record_user.t_u_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    @Column(name = "t_u_id")
    private Long markPeople;

    public Long getMarkPeople() {
        return markPeople;
    }

    public void setMarkPeople(Long markPeople) {
        this.markPeople = markPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record_user.t_p_id
     *
     * @return the value of t_exam_publish_record_user.t_p_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public Long getPublishId() {
        return publishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record_user.t_p_id
     *
     * @param paperId the value for t_exam_publish_record_user.t_p_id
     *
     * @mbggenerated Tue Jul 07 18:01:22 CST 2020
     */
    public void setPublishId(Long paperId) {
        this.publishId = paperId;
    }


}