spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
    gateway:
      routes:
        - id: boss-bes-authentication
          uri: lb://boss-bes-authentication
          order: 0
          predicates:
            - Path=/auth/**
          # 去除前缀
          filters:
            - StripPrefix=1

  # 组nacos和seata服务地址
  nacos-url:
    nacos-host: 123.57.156.184
    nacos-port: 8848
  seata-url:
    seata-host: 123.57.156.184
    seata-port: 8091