spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
    gateway:
      routes:
        - id: boss-bes-authentication
          uri: lb://boss-bes-authentication
          order: 0
          predicates:
            - Path=/auth/**
          # 去除前缀
          filters:
            - StripPrefix=1
        - id: boss-bes-system
          uri: lb://boss-bes-system
          order: 0
          predicates:
            - Path=/system/**
          # 去除前缀
          filters:
            - StripPrefix=1
        - id: boss-bes-exam
          uri: lb://boss-bes-exam
          order: 0
          predicates:
            - Path=/exam/**
          # 去除前缀
          filters:
            - StripPrefix=1
        - id: boss-bes-basedata
          uri: lb://boss-bes-basedata
          order: 0
          predicates:
            - Path=/basedata/**
          # 去除前缀
          filters:
            - StripPrefix=1
        - id: boss-bes-paper
          uri: lb://boss-bes-paper
          order: 0
          predicates:
            - Path=/paper/**
          # 去除前缀
          filters:
            - StripPrefix=1
    #sentinel:
        #transport:
        # dashboard: localhost:8080 #配置sentinel dashboard地址
        #port: 8719
  #service-url:
  #boss-bes-system-center: http://boss-bes-system-center

  # 组nacos和seata服务地址
  nacos-url:
    nacos-host: 123.57.156.184
#    nacos-host: 39.97.106.243
    nacos-port: 8848
  seata-url:
    seata-host: 123.57.156.184
    seata-port: 8091