package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;
import io.swagger.models.auth.In;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

@Table(name = "t_exam_answer_record")
public class AnswerRecord extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.t_r_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long tRId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.my_answer
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private String myAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.standard_answer
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private String standardAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private String evaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.status
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.company_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.org_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.created_by
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.created_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.updated_by
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.updated_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_answer_record.version
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.id
     *
     * @return the value of t_exam_answer_record.id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.id
     *
     * @param id the value for t_exam_answer_record.id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.t_r_id
     *
     * @return the value of t_exam_answer_record.t_r_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long gettRId() {
        return tRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.t_r_id
     *
     * @param tRId the value for t_exam_answer_record.t_r_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void settRId(Long tRId) {
        this.tRId = tRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.my_answer
     *
     * @return the value of t_exam_answer_record.my_answer
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getMyAnswer() {
        return myAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.my_answer
     *
     * @param myAnswer the value for t_exam_answer_record.my_answer
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMyAnswer(String myAnswer) {
        this.myAnswer = myAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.standard_answer
     *
     * @return the value of t_exam_answer_record.standard_answer
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getStandardAnswer() {
        return standardAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.standard_answer
     *
     * @param standardAnswer the value for t_exam_answer_record.standard_answer
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setStandardAnswer(String standardAnswer) {
        this.standardAnswer = standardAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.score
     *
     * @return the value of t_exam_answer_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.score
     *
     * @param score the value for t_exam_answer_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.evaluate
     *
     * @return the value of t_exam_answer_record.evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.evaluate
     *
     * @param evaluate the value for t_exam_answer_record.evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.status
     *
     * @return the value of t_exam_answer_record.status
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.status
     *
     * @param status the value for t_exam_answer_record.status
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.company_id
     *
     * @return the value of t_exam_answer_record.company_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.company_id
     *
     * @param companyId the value for t_exam_answer_record.company_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.org_id
     *
     * @return the value of t_exam_answer_record.org_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.org_id
     *
     * @param orgId the value for t_exam_answer_record.org_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.created_by
     *
     * @return the value of t_exam_answer_record.created_by
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.created_by
     *
     * @param createdBy the value for t_exam_answer_record.created_by
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.created_time
     *
     * @return the value of t_exam_answer_record.created_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.created_time
     *
     * @param createdTime the value for t_exam_answer_record.created_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.updated_by
     *
     * @return the value of t_exam_answer_record.updated_by
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.updated_by
     *
     * @param updatedBy the value for t_exam_answer_record.updated_by
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.updated_time
     *
     * @return the value of t_exam_answer_record.updated_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.updated_time
     *
     * @param updatedTime the value for t_exam_answer_record.updated_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_answer_record.version
     *
     * @return the value of t_exam_answer_record.version
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_answer_record.version
     *
     * @param version the value for t_exam_answer_record.version
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}