package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;
import java.util.Date;
import javax.persistence.*;

@Table(name = "t_exam_publish_record")
public class ExamPublishRecord extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "t_p_id")
    private Long paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.title
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "title")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.publisher
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "publisher")
    private Long publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "start_time")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "end_time")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.plan_pepole_num
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "plan_people_num")
    private Integer planPeopleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.limit_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "limit_time")
    private Integer limitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.description
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "description")
    private String description;

    /**
     * 阅卷方式
     * This field corresponds to the database column t_exam_publish_record.marking_mode
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "marking_mode")
    private Integer markingMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.marking_stop_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "marking_stop_time")
    private Date markingStopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.qrcode_url
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "qrcode_url")
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.field1
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "field1")
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_publish_record.field2
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    @Column(name = "field2")
    private String field2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.t_p_id
     *
     * @return the value of t_exam_publish_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.t_p_id
     *
     * @param paperId the value for t_exam_publish_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.title
     *
     * @return the value of t_exam_publish_record.title
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.title
     *
     * @param title the value for t_exam_publish_record.title
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.publisher
     *
     * @return the value of t_exam_publish_record.publisher
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.publisher
     *
     * @param publisher the value for t_exam_publish_record.publisher
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPublisher(Long publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.start_time
     *
     * @return the value of t_exam_publish_record.start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.start_time
     *
     * @param startTime the value for t_exam_publish_record.start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.end_time
     *
     * @return the value of t_exam_publish_record.end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.end_time
     *
     * @param endTime the value for t_exam_publish_record.end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.plan_pepole_num
     *
     * @return the value of t_exam_publish_record.plan_pepole_num
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Integer getPlanPeopleNum() {
        return planPeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.plan_pepole_num
     *
     * @param planPeopleNum the value for t_exam_publish_record.plan_pepole_num
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPlanPeopleNum(Integer planPeopleNum) {
        this.planPeopleNum = planPeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.limit_time
     *
     * @return the value of t_exam_publish_record.limit_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Integer getLimitTime() {
        return limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.limit_time
     *
     * @param limitTime the value for t_exam_publish_record.limit_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setLimitTime(Integer limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.description
     *
     * @return the value of t_exam_publish_record.description
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.description
     *
     * @param description the value for t_exam_publish_record.description
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.marking_mode
     *
     * @return the value of t_exam_publish_record.marking_mode
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Integer getMarkingMode() {
        return markingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.marking_mode
     *
     * @param markingMode the value for t_exam_publish_record.marking_mode
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMarkingMode(Integer markingMode) {
        this.markingMode = markingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.marking_stop_time
     *
     * @return the value of t_exam_publish_record.marking_stop_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getMarkingStopTime() {
        return markingStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.marking_stop_time
     *
     * @param markingStopTime the value for t_exam_publish_record.marking_stop_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMarkingStopTime(Date markingStopTime) {
        this.markingStopTime = markingStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.qrcode_url
     *
     * @return the value of t_exam_publish_record.qrcode_url
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.qrcode_url
     *
     * @param qrcodeUrl the value for t_exam_publish_record.qrcode_url
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.field1
     *
     * @return the value of t_exam_publish_record.field1
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.field1
     *
     * @param field1 the value for t_exam_publish_record.field1
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_publish_record.field2
     *
     * @return the value of t_exam_publish_record.field2
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_publish_record.field2
     *
     * @param field2 the value for t_exam_publish_record.field2
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setField2(String field2) {
        this.field2 = field2;
    }
}