package com.boss.xtrain.exam.pojo.entity;

import com.boss.xtrain.common.core.pojo.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

@Table(name = "t_exam_record")
public class ExamRecord extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.t_pr_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long tPId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.plan_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date planStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.plan_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.actual_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date actualStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.actual_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date actualEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.objective_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private BigDecimal objectiveSubjectScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.t_u_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Long tUId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.subjectvie_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private BigDecimal subjectvieSubjectScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.marking_assign_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private Date markingAssignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_record.system_evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    private String systemEvaluate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.id
     *
     * @return the value of t_exam_record.id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.id
     *
     * @param id the value for t_exam_record.id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.t_pr_id
     *
     * @return the value of t_exam_record.t_pr_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.t_pr_id
     *
     * @param paperId the value for t_exam_record.t_pr_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.t_p_id
     *
     * @return the value of t_exam_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long gettPId() {
        return tPId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.t_p_id
     *
     * @param tPId the value for t_exam_record.t_p_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void settPId(Long tPId) {
        this.tPId = tPId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.plan_start_time
     *
     * @return the value of t_exam_record.plan_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getPlanStartTime() {
        return planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.plan_start_time
     *
     * @param planStartTime the value for t_exam_record.plan_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.plan_end_time
     *
     * @return the value of t_exam_record.plan_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.plan_end_time
     *
     * @param planEndTime the value for t_exam_record.plan_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.actual_start_time
     *
     * @return the value of t_exam_record.actual_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getActualStartTime() {
        return actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.actual_start_time
     *
     * @param actualStartTime the value for t_exam_record.actual_start_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setActualStartTime(Date actualStartTime) {
        this.actualStartTime = actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.actual_end_time
     *
     * @return the value of t_exam_record.actual_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getActualEndTime() {
        return actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.actual_end_time
     *
     * @param actualEndTime the value for t_exam_record.actual_end_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setActualEndTime(Date actualEndTime) {
        this.actualEndTime = actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.objective_subject_score
     *
     * @return the value of t_exam_record.objective_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public BigDecimal getObjectiveSubjectScore() {
        return objectiveSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.objective_subject_score
     *
     * @param objectiveSubjectScore the value for t_exam_record.objective_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setObjectiveSubjectScore(BigDecimal objectiveSubjectScore) {
        this.objectiveSubjectScore = objectiveSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.t_u_id
     *
     * @return the value of t_exam_record.t_u_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Long gettUId() {
        return tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.t_u_id
     *
     * @param tUId the value for t_exam_record.t_u_id
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void settUId(Long tUId) {
        this.tUId = tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.subjectvie_subject_score
     *
     * @return the value of t_exam_record.subjectvie_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public BigDecimal getSubjectvieSubjectScore() {
        return subjectvieSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.subjectvie_subject_score
     *
     * @param subjectvieSubjectScore the value for t_exam_record.subjectvie_subject_score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setSubjectvieSubjectScore(BigDecimal subjectvieSubjectScore) {
        this.subjectvieSubjectScore = subjectvieSubjectScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.marking_assign_time
     *
     * @return the value of t_exam_record.marking_assign_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public Date getMarkingAssignTime() {
        return markingAssignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.marking_assign_time
     *
     * @param markingAssignTime the value for t_exam_record.marking_assign_time
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setMarkingAssignTime(Date markingAssignTime) {
        this.markingAssignTime = markingAssignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.score
     *
     * @return the value of t_exam_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.score
     *
     * @param score the value for t_exam_record.score
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_record.system_evaluate
     *
     * @return the value of t_exam_record.system_evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public String getSystemEvaluate() {
        return systemEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_record.system_evaluate
     *
     * @param systemEvaluate the value for t_exam_record.system_evaluate
     *
     * @mbggenerated Tue Jul 07 17:49:29 CST 2020
     */
    public void setSystemEvaluate(String systemEvaluate) {
        this.systemEvaluate = systemEvaluate;
    }

}