spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}

  # druid 数据源配置 根据自己的微服务数据库信息配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bosstrain
    password: Boss20Train@#$
    url: jdbc:mysql://123.57.156.184:3306/alidb_test?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false

  # 组内使用统一的nacos和seata服务 这部分信息可以不用修改
  nacos-url:
    nacos-host: 123.57.156.184
    nacos-port: 8848
  seata-url:
    seata-host: 123.57.156.184
    seata-port: 8091

seata:
  enabled: true
  application-id: ${spring.application.name} # 可自定义，目前设置为微服务应用名，不需要修改

  # 这里的 tx-service-group 分布式事务组，要和服务端保持一致
  tx-service-group: base-data-group

  # 指定注册中心和配置中心 用来读取原来的registry.conf和file.conf信息 不需要自行修改
  # 这里使用 file 模式
  config:
    type: file
    # nacos的方式还没有找到解决的办法
    nacos:
      namespace: ""
      server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: file
    # nacos的方式还没有找到解决的办法
    nacos:
      application: seata-server
      server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
      namespace: ""
      userName: nacos
      password: nacos

  ##### 服务配置项 对应 file.conf #####
  service:
    # 分组和 Seata 服务的映射 默认端口8091
    grouplist:
      default: ${spring.seata-url.seata-host}:${spring.seata-url.seata-port}
    vgroupMapping:

      # 这里的 demo1-server-group 改为与服务端一致的分布式事务组名
      base-data-group: default

    disable-global-transaction: false
  # 以下配置一般不需要进行修改
  transport:
    type: TCP
    server: NIO
    heartbeat: true
    enable-client-batch-send-request: false
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyServerNIOWorker
      boss-thread-size: 1
      worker-thread-size: default
    shutdown:
      wait: 3
    serialization: seata
    compressor: none
