server:
  port: 18001

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.178.139:3306/db_system_center?serverTimezone=Asia/Shanghai&useAffectedRows=true&characterEncoding=utf8
    username: root
    password: zzy873190934
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10

  application:
    name: boss-bes-system
  redis:
    host: 39.97.106.243 #123.57.156.184:6379
    password: 991018 #bosstrain@14`

  nacos-url:
#    nacos-host: 39.97.106.243
    #    nacos-host: 123.57.156.184
    nacos-host: 39.97.106.243
    nacos-port: 8848

security:
  oauth2:
    client:
      clientId: bes
      clientSecret: 12345
      userAuthorizationUri: http://localhost:18006/oauth/authorize
      grant-type: password
      scope: read
      access-token-uri: http://localhost:18006/oauth/token
    resource:
      token-info-uri: http://localhost:18006/oauth/check_token
      user-info-uri: http://localhost:18006/user
    authorization:
      check-token-access: http://localhost:18006/oauth/check_token
  #cloud:
    #nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      #discovery:
        #server-addr: 39.97.106.243:8848 # Nacos 服务器地址
        #service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  # spring.datasource.url=jdbc:mysql://39.101.178.139:3306/db_system_center?serverTimezone=Asia/Shanghai
  # spring.datasource.username=root
  # spring.datasource.password=zzy873190934

  # mapper.mappers=tk.mybatis.mapper.common.Mapper
  # mapper.not-empty=true

  # mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
  # mybatis.type-aliases-package=com.boss.xtrain.permission.pojo.entity
  # mybatis.configuration.map-underscore-to-camel-case=true

  # pagehelper.helper-dialect=mysql
  # pagehelper.reasonable=true
  # pagehelper.support-methods-arguments=true
  # pagehelper.params=count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boss.xtrain.permission.pojo.entity
  configuration.map-underscore-to-camel-case: true
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countsql
