#spring
spring:
  datasource:
    url: jdbc:yundatabase://39.101.178.139:3306/db_system_center?serverTimezone=UTC
    username: root
    password: zzy873190934
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.boss.bes.permission.pojo.dto
  mapper-locations: classpath:mapper/*.xml