package com.boss.xtrain.common.util;

import com.boss.xtrain.common.core.aspect.EntityFields;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;
@Slf4j
public class JwtUtilsTest {
    @Test
    public void testJwt(){
        EntityFields result = JwtUtils.getInfoFromToken("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBhcnRtZW50TmFtZSI6InJlbnppIiwidXNlcl9uYW1lIjoibGlsZWkiLCJjb21wYW55TmFtZSI6InRyeTExMSIsImRlcGFydG1lbnRJZCI6MSwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifSx7ImF1dGhvcml0eSI6IuaMiemSrui1hOa6kCJ9XSwiY2xpZW50X2lkIjoiYmVzIiwib3JnYW5pemF0aW9uSWQiOjEyODI1MDg2NzI3MzU0OTQxNDQsImNvbXBhbnlJZCI6MTI4MzIwNTg5NjE0MjQ0NjU5Miwic2NvcGUiOlsicmVhZCJdLCJpZCI6MTExMSwiZXhwIjoxNTk1MTQ3Njg4LCJqdGkiOiI4ZDA4NDEyYy03YzRiLTQ5YTMtYTExNy1iNzI0YWE3NjBlMjMiLCJ1c2VybmFtZSI6ImxpbGVpIn0.i3ZzWAtGi3hkwKGPG-4ZqetBt3FzLeljQ32ANzpszqBNW_e6gV6x_Lvd3eDnyurjEgDRha-wFN3SskGurIAzgGgwowIdR4YJInE-djAOQ9K0F1Tu5hNa5XO9SajPYPBRZZS7FiY81obxqTmS6CLArdN3zBUCnvSi4EFDBABTBsHGyKZ7myhflVhIGW3l-_6c7oDTVUX6V0lUhwvijdeC4ZMVc2y8wbHp9VpG2K0qZpq_-WGEvUMPIHDHljrjPVSZS3JbzPq0pRyOXKJ22nBQtxKyZmjdIevhKSQNQ2Jotf23zPU-0kQMjchWekXf5JoJsASqZLmtXzhodGpzfv7l4Q");
        log.info(result.toString());
    }
}