spring:
  application:
    name: exam-center # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 39.97.106.243:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.178.139:3306/db_exam_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    password: zzy873190934
    username: root
    hikari:
      connection-timeout: 10000
  #    url: jdbc:mysql://39.97.106.243:3306/db_exam_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#    password: 991018
  redis:
    host: 39.97.106.243
    password: 991018

# mybatis
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.boss.xtrain.exam.pojo.entity

  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

# pagehelper
pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countsql

server:
  port: 18080 # 服务器端口。默认为 8080