spring:
  application:
    name: boss-bes-exam # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        # server-addr: 39.97.106.243:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
        server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.178.139:3306/db_exam_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    password: zzy873190934
    username: root
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
  #    url: jdbc:mysql://39.97.106.243:3306/db_exam_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#    password: 991018
  redis:
    host: 39.97.106.243
    password: 991018
  # nacos链接和密码
  nacos-url:
    nacos-host: 123.57.156.184
    nacos-port: 8848
  security:-url:
    host: localhost
    port: 18006

# 配置资源服务器
security:
  oauth2:
    client:
      clientId: bes
      clientSecret: 12345
      userAuthorizationUri: http://${spring.security-url.host}:${spring.security-url.port}/oauth/authorize
      grant-type: password
      scope: read
      access-token-uri: http://${spring.security-url.host}:${spring.security-url.port}/oauth/token
    resource:
      token-info-uri: http://${spring.security-url.host}:${spring.security-url.port}/oauth/check_token
      user-info-uri: http://${spring.security-url.host}:${spring.security-url.port}/user
    authorization:
      check-token-access: http://${spring.security-url.host}:${spring.security-url.port}/check_token

# mybatis
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.boss.xtrain.exam.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

# pagehelper
pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countsql

server:
  port: 18003 # 服务器端口。默认为 8080
feign:
  hystrix:
    enabled: true