spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.nacos-url.nacos-host}:${spring.nacos-url.nacos-port}
    # druid 数据源配置 根据自己的微服务数据库信息配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bosstrain
    password: Boss20Train@#$
    url: jdbc:mysql://123.57.156.184:3306/db_sys_manager_center?useUnicode=true&serverTimezone=UTC&useSSL=false
  redis:
    database: 0
    # Redis服务器地址
    host: 123.57.156.184
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: bosstrain@14
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 1024
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接池中的最大空闲连接
        max-idle: 200
    # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000

  # 组nacos和seata服务地址
  nacos-url:
    nacos-host: 39.97.106.243
#    nacos-host: 39.97.106.243
    nacos-port: 8848
  seata-url:
    seata-host: 123.57.156.184
    seata-port: 8091

#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/user
      prefer-token-info: false
# feign调用超时时间配置
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
  #sentinel:
    #enabled: true

# Generator
generator:
  targetProject: src/main/java
  mappers: com.boss.xtrain.common.core.web.dao.CommonMapper
  javaModel-targetPackage: com.boss.xtrain.authentication.pojo
  sqlMap-targetPackage: mapper
  javaClient-targetPackage: com.boss.xtrain.authentication.mapper
mybatis:
  mapper-locations: classpath:mapper/*.xml
